# Generated by Django 4.1.5 on 2023-01-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Имя')),
                ('number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('summ', models.CharField(max_length=10, verbose_name='Имя')),
                ('telegram', models.CharField(max_length=70, verbose_name='Никнейм в телеграме')),
                ('message', models.TextField(verbose_name='Коментарий')),
                ('date', models.DateTimeField(verbose_name='Дата')),
            ],
        ),
    ]
