# Generated by Django 4.1.5 on 2023-01-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Лид', 'verbose_name_plural': 'Лиды'},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='date',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='summ',
            field=models.CharField(max_length=10, verbose_name='Сумма обмена'),
        ),
    ]
